<?php
$searchRoute = $this->searchOptions($this->driver->getSourceIdentifier())->getSearchAction();
$phraseSearch = $this->lookfor['phraseSearch'] ?? true;
$lookFor = $this->lookfor['lookfor'] ?? '';
$searchType = $this->lookfor['searchType'] ?? 'AllFields'
?>
<?=$this->url($searchRoute)?>?lookfor=<?=(($phraseSearch) ? '%22'.urlencode($lookFor).'%22' : urlencode($lookFor))?>&amp;type=<?=$searchType?>
